package src;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JPanel;
import panels.FilterPanel;
import panels.LoginCheckPanel;
import sun.swing.FilePane;

/**
 *
 * @author Nico Hribar
 */
public class MamaGUI extends JFrame {

    private TableModel tableModel = new TableModel();

    /**
     * Creates new form MamaGUI2
     */
    public MamaGUI() {
        initComponents();
        setLocationRelativeTo(null);

        table1.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                tableModel.clickedOn(table1.getSelectedRow());
            }
        });
        table1.setModel(tableModel);

        this.getContentPane().setBackground(Color.WHITE);
    }

    /*public MamaGUI(int index) {
        initComponents();
        
        dlSelect.setSelectedIndex(index);
    }*/
    String buttonName;

    public MamaGUI(String buttonName) {
        initComponents();
        setLocationRelativeTo(null);

        table1.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                tableModel.clickedOn(table1.getSelectedRow());
            }
        });
        table1.setModel(tableModel);

        this.getContentPane().setBackground(Color.WHITE);
        this.buttonName = buttonName;

        DefaultComboBoxModel comboBoxModel = (DefaultComboBoxModel) dlSelect.getModel();

        if (comboBoxModel.getIndexOf(buttonName) == -1) {
            comboBoxModel.addElement(buttonName);
        }
        //dlSelect.setSelectedIndex(Integer.parseInt(buttonName.substring(5))); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Tables = new javax.swing.JPanel();
        ScrollPane = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        Buttons = new javax.swing.JPanel();
        btAdd = new javax.swing.JButton();
        btEdit = new javax.swing.JButton();
        btDelete = new javax.swing.JButton();
        btLogin = new javax.swing.JButton();
        dlSelect = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        about = new javax.swing.JMenuItem();
        help = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        csvImport = new javax.swing.JMenuItem();
        logout = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Big Mama Management Software");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("ZF_Logo.png")));

        Tables.setLayout(new java.awt.GridLayout(1, 0));

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table1.setBackground(Color.WHITE);
        ScrollPane.setViewportView(table1);

        Tables.add(ScrollPane);
        ScrollPane.setBackground(Color.WHITE);

        getContentPane().add(Tables, java.awt.BorderLayout.CENTER);
        Tables.setBackground(Color.WHITE);

        Buttons.setLayout(new java.awt.GridLayout(1, 0));

        btAdd.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        //btAdd.setBorder(new RoundedBorder(10)); //10 is the radius
        btAdd.setForeground(Color.WHITE);
        btAdd.setBackground(Color.decode("#1179BF"));
        btAdd.setText("Hinzüfgen");
        btAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btAddMousePressed(evt);
            }
        });
        Buttons.add(btAdd);

        btEdit.setFont(new java.awt.Font("Verdana", 1, 12));
        btEdit.setForeground(Color.WHITE);
        btEdit.setBackground(Color.decode("#1179BF"));
        btEdit.setText("Bearbeiten");
        //btEdit.setText("<html><div style='background-color: orange;width:100% !important;height:100% !important;'> test </div></html>");
        Buttons.add(btEdit);

        btDelete.setFont(new java.awt.Font("Verdana", 1, 12));
        btDelete.setForeground(Color.WHITE);
        btDelete.setBackground(Color.decode("#1179BF"));
        btDelete.setText("Löschen");
        Buttons.add(btDelete);

        btLogin.setFont(new java.awt.Font("Verdana", 1, 12));
        btLogin.setForeground(Color.WHITE);
        btLogin.setBackground(Color.decode("#1179BF"));
        btLogin.setText("Login");
        btLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btLoginMousePressed(evt);
            }
        });
        Buttons.add(btLogin);

        dlSelect.setForeground(Color.WHITE);
        dlSelect.setBackground(Color.decode("#1179BF"));
        dlSelect.setFont(new java.awt.Font("Verdana", 1, 12));
        dlSelect.setForeground(new java.awt.Color(255, 255, 255));
        dlSelect.setSelectedItem(null);
        Buttons.add(dlSelect);

        getContentPane().add(Buttons, java.awt.BorderLayout.SOUTH);
        Buttons.setBackground(Color.WHITE);

        fileMenu.setText("File");

        about.setText("About");
        fileMenu.add(about);

        help.setText("Help");
        fileMenu.add(help);

        jMenuBar1.add(fileMenu);

        editMenu.setText("Edit");

        csvImport.setText("Import from CSV");
        csvImport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                csvImportMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                csvImportMousePressed(evt);
            }
        });
        csvImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                csvImportActionPerformed(evt);
            }
        });
        editMenu.add(csvImport);

        logout.setText("Logout");
        editMenu.add(logout);

        jMenuBar1.add(editMenu);

        jMenu1.setText("Filter");
        jMenu1.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                onShowFilter(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAddMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAddMousePressed

    }//GEN-LAST:event_btAddMousePressed

    private void btLoginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btLoginMousePressed
        createFrame(new LoginCheckPanel());
    }//GEN-LAST:event_btLoginMousePressed

    private void csvImportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_csvImportMouseClicked

    }//GEN-LAST:event_csvImportMouseClicked

    private void csvImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_csvImportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_csvImportActionPerformed

    private void csvImportMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_csvImportMousePressed
        System.out.println("CSV Import Button");
    }//GEN-LAST:event_csvImportMousePressed

    private void onShowFilter(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onShowFilter
        createFrame(new FilterPanel());
    }//GEN-LAST:event_onShowFilter

    public void createFrame(JPanel panel) {
        JFrame frame = new JFrame();
        frame.add(panel);
        frame.setVisible(true);
        frame.setSize(500, 300);
        frame.setLocationRelativeTo(null);

        if (panel instanceof FilterPanel) {
            frame.setLocationRelativeTo(this);
            frame.addWindowListener(new WindowAdapter() {
                public void windowClosing(WindowEvent e) {
                    tableModel.loadFromDB();
                }

            });
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MamaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MamaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MamaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MamaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MamaGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Buttons;
    private javax.swing.JScrollPane ScrollPane;
    private javax.swing.JPanel Tables;
    private javax.swing.JMenuItem about;
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btEdit;
    private javax.swing.JButton btLogin;
    private javax.swing.JMenuItem csvImport;
    private javax.swing.JComboBox<String> dlSelect;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem help;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem logout;
    private javax.swing.JTable table1;
    // End of variables declaration//GEN-END:variables
}
