
<<<<<<< Updated upstream:DBTool_Test/src/StartMenu.java


=======
<<<<<<< HEAD:DBTool_Test/src/StartMenu.java
=======
import java.awt.Toolkit;
import java.io.File;
import java.io.FileFilter;
>>>>>>> master:DB-Tool/src/StartMenu.java
import javax.swing.JButton;
import java.awt.Color;
>>>>>>> Stashed changes:DB-Tool/src/StartMenu.java
import java.awt.Toolkit;
import java.io.File;
import java.io.FileFilter;
import javax.swing.JButton;
import javax.swing.filechooser.FileNameExtensionFilter;

import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Nico Hribar
 */
public class StartMenu extends javax.swing.JFrame {

    /**
     * Creates new form StartMenu
     */
    public StartMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btTable1 = new javax.swing.JButton();
        btTable2 = new javax.swing.JButton();
        btTable3 = new javax.swing.JButton();
        fileChooser = new javax.swing.JFileChooser();

        btTable1.setText("Table1");
        btTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onChooseTableButtonClicked(evt);
            }
        });

        btTable2.setText("Table2");
        btTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onChooseTableButtonClicked(evt);
            }
        });

        btTable3.setText("Table3");
        btTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onChooseTableButtonClicked(evt);
            }
        });
<<<<<<< Updated upstream:DBTool_Test/src/StartMenu.java

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Choose .csv file for import");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("ZF_Logo.png")));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        fileChooser.setAcceptAllFileFilterUsed(false);
        FileNameExtensionFilter filter = new FileNameExtensionFilter(".csv Files", "csv");
        fileChooser.setFileFilter(filter);
        //fileChooser.showOpenDialog(frame);
        File selectedFile = fileChooser.getSelectedFile();
        fileChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileChooserActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.RELATIVE;
        getContentPane().add(fileChooser, gridBagConstraints);
=======
<<<<<<< HEAD:DBTool_Test/src/StartMenu.java
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 100;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(btTable3, gridBagConstraints);
=======

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Choose .csv file for import");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("ZF_Logo.png")));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        fileChooser.setAcceptAllFileFilterUsed(false);
        FileNameExtensionFilter filter = new FileNameExtensionFilter(".csv Files", "csv");
        fileChooser.setFileFilter(filter);
        //fileChooser.showOpenDialog(frame);
        File selectedFile = fileChooser.getSelectedFile();
        fileChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileChooserActionPerformed(evt);
            }
        });
        getContentPane().add(fileChooser, new java.awt.GridBagConstraints());
>>>>>>> master:DB-Tool/src/StartMenu.java
>>>>>>> Stashed changes:DB-Tool/src/StartMenu.java

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onChooseTableButtonClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onChooseTableButtonClicked
        JButton button = (JButton) evt.getSource();
        System.out.println(button.getText());
        this.setVisible(false);
        //new MamaGUI().setVisible(true);
    }//GEN-LAST:event_onChooseTableButtonClicked

    private void fileChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileChooserActionPerformed
        if (evt.getActionCommand().equals(javax.swing.JFileChooser.APPROVE_SELECTION)) {
            System.out.println("TODO: Open File");
        } else if (evt.getActionCommand().equals(javax.swing.JFileChooser.CANCEL_SELECTION)) {
            this.setVisible(false);
        }
    }//GEN-LAST:event_fileChooserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btTable1;
    private javax.swing.JButton btTable2;
    private javax.swing.JButton btTable3;
    private javax.swing.JFileChooser fileChooser;
    // End of variables declaration//GEN-END:variables
}
