/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panels;

import data.SQLResult;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.*;
import src.DatabaseGateway;

/**
 *
 * @author tobia
 */
public class FilterPanel extends javax.swing.JPanel {

    DatabaseGateway dbgw = DatabaseGateway.getInstance();
    List<ArrayList<String>> tables = new ArrayList<>();
    List<ArrayList<String>> values = new ArrayList<>();

    /**
     * Creates new form FilterPanel
     */
    public FilterPanel() {
        initComponents();
        initComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbTables = new javax.swing.JComboBox<>();
        cbValues = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setEnabled(false);
        setLayout(new java.awt.GridLayout(0, 2));

        cbTables.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbTablesMouseClicked(evt);
            }
        });
        add(cbTables);

        add(cbValues);
        add(jTextField1);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onFilter(evt);
            }
        });
        add(jButton1);
    }// </editor-fold>//GEN-END:initComponents

    private void onFilter(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onFilter
        dbgw.searchFor("Linie", jTextField1.getText());
    }//GEN-LAST:event_onFilter

    private void cbTablesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbTablesMouseClicked

    }//GEN-LAST:event_cbTablesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbTables;
    private javax.swing.JComboBox<String> cbValues;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    private void initComboBox() {
        SQLResult result = dbgw.runQuery("SELECT table_name FROM information_schema.tables");
        tables = result.getRows();
        for (ArrayList<String> list : tables) {
            for (String s : list) {
                if (!(s.equals("MaterialProjekt") || s.equals("sysdiagrams"))) {
                    cbTables.addItem(s);
                }
            }
        }

        cbTables.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                if (e.getStateChange() == ItemEvent.SELECTED) {
                    cbValues.removeAllItems();
                    
                    for (ArrayList<String> l : dbgw.runQuery("SELECT BEZEICHNUNG FROM " + cbTables.getSelectedItem()).getRows()) {
                        for (String s : l) {
                            cbValues.addItem(s);
                        }
                    }
                }
            }

        }
        );
    }
}
