package panels;

import java.sql.Connection;
import javax.swing.JOptionPane;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author tobia
 */
public class LoginCheckPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoginCheckPanel
     */
    public LoginCheckPanel() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfUsername = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        pfPassword = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        cbUsertype = new javax.swing.JComboBox<>();
        btSign = new javax.swing.JButton();
        btReset = new javax.swing.JButton();

        setLayout(new java.awt.GridLayout(0, 2, 0, 10));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Username");
        add(jLabel1);

        tfUsername.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUsernameActionPerformed(evt);
            }
        });
        add(tfUsername);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Password");
        add(jLabel2);
        add(pfPassword);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Please select a user type");
        add(jLabel3);

        cbUsertype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "admin", "superuser" }));
        add(cbUsertype);

        btSign.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btSign.setText("Sign In");
        btSign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSignActionPerformed(evt);
            }
        });
        add(btSign);

        btReset.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btReset.setText("Reset");
        btReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btResetActionPerformed(evt);
            }
        });
        add(btReset);
    }// </editor-fold>//GEN-END:initComponents

    private void tfUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUsernameActionPerformed

    }//GEN-LAST:event_tfUsernameActionPerformed

    private void btResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btResetActionPerformed
        tfUsername.setText("");
        pfPassword.setText("");
    }//GEN-LAST:event_btResetActionPerformed

    private void btSignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSignActionPerformed
        try {
            String url = "jdbc:sqlserver://localhost:1433;databaseName=testdb;username=sa;password=BMeu/k45671";
            Connection conn = DriverManager.getConnection(url);
            String sql = "Select * FROM testlogin where username=? and password = ? and usertype = ?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, tfUsername.getText());
            pst.setString(2, pfPassword.getText());
            pst.setString(3, String.valueOf(cbUsertype.getSelectedItem()));
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                JOptionPane.showMessageDialog(null, "Username and Password matched!"
                    + " You are now logged in as " + rs.getString("usertype"));
                if (cbUsertype.getSelectedIndex() == 0) {
//                    admin a = new admin();
//                    a.setVisible(true);
//                    this.setVisible(false);
                } else if (cbUsertype.getSelectedIndex() == 1) {
//                    superuser s = new superuser();
//                    s.setVisible(true);
//                    this.setVisible(false);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Incorrect Username or Password");
                tfUsername.setText("");
                pfPassword.setText("");

            }
            conn.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btSignActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btReset;
    private javax.swing.JButton btSign;
    private javax.swing.JComboBox<String> cbUsertype;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField pfPassword;
    private javax.swing.JTextField tfUsername;
    // End of variables declaration//GEN-END:variables
}
